apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - astronauts.yaml
  - gateway.yaml
  - missions.yaml
configMapGenerator:
  - name: gateway-files
    files:
      - ./supergraph.graphql
      - ./config.yaml
generatorOptions:
  # a deterministic configmap name makes it possible to swap the supergraph SDL
  # by update the configmap
  disableNameSuffixHash: true
